trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
- script: dotnet build ./ApressSolution --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: UseDotNet@2
- script: dotnet test ./ApressSolution/ApressSolution.Test
  displayName: 'dotnet test'